//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbrs_marmara_api_v1._0.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int id { get; set; }
        public Nullable<int> task_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> reward_status { get; set; }
    }
}
